#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: baobao123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

  application:
    name: springboot-transcational

  messages:
    encoding: UTF-8


  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: baobao123
    database: 0
    jedis:
      pool:
        max-active: 50
        max-wait: 3000
        max-idle: 20
        min-idle: 2
    timeout: 5000

#配置mybatis
mybatis:
  typeAliasesPackage: com.hyouka.school.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #    打印结果
    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    不打印结果
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true


#配置mapper
mapper:
  not-empty: false
  identity: MYSQL

#配置Tomcat，配置80，可在浏览器访问项目时不用加端口号（默认端口8080）
server:
  tomcat:
    uri-encoding: UTF-8
  port: 80

logging:
  level:
    com.hyouka.school.mapper: debug
  config: classpath:log4j2.yml
