#配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: baobao123
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp

#配置mybatis
mybatis:
  typeAliasesPackage: com.hyouka.school.domain
  mapper-locations: classpath:mapper/*.xml

#配置mapper
mapper:
  not-empty: false
  identity: MYSQL

#配置Tomcat，配置80，可在浏览器访问项目时不用加端口号（默认端口8080）
server:
  port: 80
